services:
  strapi:
    container_name: fini-kreativ-strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fini-kreativ-strapi:latest
    env_file: .env
    depends_on:
      - database
    networks:
      - strapi_internal
      - traefik_proxy
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: production
    volumes:
      - "${DATA}/uploads:/opt/app/public/uploads"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls=true"
      - "traefik.http.routers.strapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"

  database:
    container_name: fini-kreativ-database
    env_file: .env
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - strapi_internal
    volumes:
      - "${DATA}/database:/var/lib/postgresql/data"
    restart: unless-stopped

networks:
  strapi_internal:
    driver: bridge
  traefik_proxy:
    name: traefik_proxy
    external: true
